<script setup>
import {activateSetup} from './miniRouter'
import setup from './components/setup.vue';
import login from './components/login.vue';

</script>

<template>
  <div>
    <!--Banner-->
    <h1 id="banner">TunnelBlazer</h1>
    <!--Powered by banner-->
    <h3>Powered by <img src="./src/assets/OpenVPN_logo.svg" width="200" height="auto" loading="lazy"></h3>
    <div id="main-container"class="container my-5">
      <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <!--I'm using Vue's if else to change between the components
        I'm using a button to trigger the change as reflected in miniRouter.js-->
        <!--As long as the condition doesnt change, the login component remains visible-->
        <login v-if="!activateSetup"/>
        <!--The second the value of activatesetup changes to false, it enables the setup component-->
        <setup v-else/>
        <!--Do not mess with this, this is the button that makes the above mechanism work. I worked for 4 hours straight to get this working-->
        <button id="setupbtn" @click="activateSetup= !activateSetup" class="btn btn-dark">Toggle Setup Mode</button>
        
      </div>
    </div>
    
    <!--Footer-->
    <div>
      <footer>
        <!--Just displaying the tech used-->
        <p>Built with <img src="./src/assets/Vuejs.svg" width="100" height="auto" loading="lazy"> </p>
        <!--Why not a mention of myself?-->
        <p>Designed and Developed by SpaciousCoder78</p>
      </footer>
    </div>
  </div>
</template>


<!--================================CSS Holy Grail======================-->
<style scoped>

#maincontainer{
  display: flex;
  justify-content: center;
  align-items: center;
}

#setupbtn{
  
  width: 40%;
  height: 40%;
  margin:auto;
  margin-bottom: 40px;
}

/*Generated by Vue app, can be deprecated*/
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
